# site
title: JS Reader
name: JS Reader
url: http://reader.js.org
githubUrl: https://github.com/ruanyl/js-reader
root: /

# post
postDir: _posts

# build
outputDir: dist

#cname
cname: reader.js.org

pageSize: 15
